export default {
  dashboard_screen: 'Dashboard',
  add_category: 'Add A Category',
  no_data: 'No Category Found',
  new_category: 'New Category',
  feild: 'Field',
  add_new_field: ' ADD NEW FIELD',
  title_field: 'TITLE FIELD',
  delete: 'DELETE',
  remove: 'REMOVE',
  unnamed_field: 'UNNAMED FIELD',
  manage_cat: 'Manage Categories',
  list_dropDown: [
    {label: 'Text'},
    {label: 'Number'},
    {label: 'CheckBox'},
    {label: 'Date'},
  ],
  user_message: 'Please add some categories first',
};
